import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {players} from "/db";

function Players() {
  return (
    <ul>
      {players.map((user) => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  )
}

const inter = Inter({ subsets: ['latin'] })

export default function Home(players) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>
          Test
        </h1>
        <Players />
      </main>
    </>
  )
}